### ISSUE TITLE
Missing x in equation 3.5

### ISSUE THREAD

**Issue by davidrosenberg** [yousuketakada/prml_errata#11]
In 3.57 on p. 156, we have p(t|t,alpha,beta).  I believe there should be an x in the conditioning too, as it is in 3.58.

**Comment by yousuketakada** [comment]
Thank you for reporting me the new errata item.
It seems that the new input vector x is omitted in (3.57) as in (3.74). However, this is inconsistent with (3.58).
I shall fix this in my errata.
