### ISSUE TITLE
Error in eq. (3.99)

### ISSUE THREAD

**Issue by eisthf** [yousuketakada/prml_errata#19]
Considering eq. (3.95), eq.(3.99) should be corrected to:

<a href="https://www.codecogs.com/eqnedit.php?latex=\beta&space;=&space;\frac{N&space;-&space;M}{2E_{D}(\mathbf{m}_N)}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\beta&space;=&space;\frac{N&space;-&space;M}{2E_{D}(\mathbf{m}_N)}" title="\beta = \frac{N - M}{2E_{D}(\mathbf{m}_N)}" /></a>

**Comment by yousuketakada** [comment]
Please note that here we consider the limit of N >> M so that N - M \to N.

**Comment by eisthf** [comment]
Ah, right.
