### ISSUE TITLE
Errata fixed by Bishop is correct at page 101? 

### ISSUE THREAD

**Issue by erdosxx** [yousuketakada/prml_errata#22]
Hi Yousuketakada

According to the official errata fix in https://www.microsoft.com/en-us/research/wp-content/uploads/2016/05/prml-errata-3rd-20110921.pdf, at page 101 ,a = 1 + beta/2 should be read a = (1 + beta)/2.
However I think that this fix is wrong and the original correct., a = 1 + beta/2.
In (2.153), lambda^(beta/2) should be lambda^(a-1) by definition of gamma function.
So, a - 1 = beta/2  --> a = 1 + beta/2
Is my understanding is correct?

**Comment by yousuketakada** [comment]
Probably you forgot the normalization factor of the Gaussian, which is dependent on lambda. Please double-check.

**Comment by erdosxx** [comment]
Thank you. You are right.
